# -*- coding: utf-8 -*-
from max.models import Activity
from max.rest import JSONResourceEntity
from max.rest import JSONResourceRoot
from max.rest import endpoint
from max.utils.dicts import flatten
from max.utils import searchParams
from max.security.permissions import add_comment
from max.security.permissions import delete_comment
from max.security.permissions import list_comments

from pyramid.httpexceptions import HTTPNoContent

import requests

@endpoint(route_name='user_comments', request_method='GET', permission=list_comments)
def getUserComments(user, request):
    """
        Get user comments

        Get all the comments generated by a user anywhere
    """
    query = {
        'object.objectType': 'comment',
        'verb': 'comment',
        'actor.username': user['username']
    }
    is_head = request.method == 'HEAD'
    comments = request.db.activity.search(
        query,
        sort="_id",
        keep_private_fields=False,
        squash=['deletable', 'favorited', 'favorites', 'faavoritesCount'],
        flatten=1,
        count=is_head,
        **searchParams(request))

    handler = JSONResourceRoot(request, comments, stats=is_head)
    return handler.buildResponse()


@endpoint(route_name='activity_comments', request_method='GET', permission=list_comments)
def getActivityComments(activity, request):
    """
        Get activity comments

        Return the comments for an activity.
    """
    replies = activity.get('replies', {})
    items = replies
    result = flatten(items, keep_private_fields=False)
    handler = JSONResourceRoot(request, result)
    return handler.buildResponse()


@endpoint(route_name='context_comments', request_method='GET', permission=list_comments)
def getContextComments(context, request):
    """
        Get context activities comments
    """
    is_head = request.method == 'HEAD'

    query = {
        'verb': 'comment',
        'object.inReplyTo.contexts': {
            '$in': [context['hash']]
        }
    }

    comments = request.db.activity.search(query, flatten=1, count=is_head, **searchParams(request))
    handler = JSONResourceRoot(request, comments, stats=is_head)
    return handler.buildResponse()


@endpoint(route_name='comments', request_method='GET', permission=list_comments)
def getGlobalComments(comments, request):
    """
        Get global comments
    """
    is_head = request.method == 'HEAD'
    activities = request.db.activity.search({'verb': 'comment'}, flatten=1, count=is_head, **searchParams(request))
    handler = JSONResourceRoot(request, activities, stats=is_head)
    return handler.buildResponse()


@endpoint(route_name='activity_comments', request_method='POST', permission=add_comment)
def addActivityComment(activity, request):
    """
        Add a comment to an activity
    """

    # Prepare rest parameters to be merged with post data
    rest_params = {
        'verb': 'comment',
        'object': {
            'inReplyTo': [{
                '_id': activity['_id'],
                'objectType': activity['object']['objectType'],
                'contexts': []
            }]
        }
    }

    # Initialize a Activity object from the request
    newactivity = Activity.from_request(request, rest_params=rest_params)

    refering_activity_contexts = activity.get('contexts', [])
    if len(refering_activity_contexts) > 0:
        context_hashes = [ctxt['hash'] for ctxt in refering_activity_contexts]
        newactivity['object']['inReplyTo'][0]['contexts'] = context_hashes

    code = 201
    newactivity_oid = newactivity.insert()
    newactivity['_id'] = newactivity_oid

    comment = dict(newactivity['object'])
    comment['published'] = newactivity['published']
    comment['actor'] = request.actor
    comment['id'] = newactivity['_id']
    del comment['inReplyTo']
    activity.addComment(comment)

    try:
        community_url = activity['contexts'][0]['url']
        site_url = '/'.join(str(community_url).split('/')[:-1])
        url = site_url + '/api/notifymail'

        payload = {"community_url": community_url,
                   "community_name": activity['contexts'][0]['displayName'],
                   "actor_displayName": comment['actor']['displayName'],
                   "activity_content": comment['content'],
                   "content_type": comment['objectType'],
                   "thumbURL": '',
                   "filename": '',
                   "mimetye": '',
                   "objectType": comment['objectType']}


        headers={'X-Oauth-Username': request.auth_headers[1],
                 'X-Oauth-Token': request.auth_headers[0],
                 'X-Oauth-Scope': request.auth_headers[2]}

        res = requests.post(url, headers=headers, data=payload, verify=False)
    except:
        pass

    handler = JSONResourceEntity(request, newactivity.flatten(), status_code=code)
    return handler.buildResponse()


@endpoint(route_name='activity_comment', request_method='DELETE', permission=delete_comment)
def deleteActivityComment(comment, request):
    """
        Delete an activity
    """
    comment.delete()
    return HTTPNoContent()
