/*
* json2
*/
var JSON;JSON||(JSON={});
(function(){function k(a){return a<10?"0"+a:a}function o(a){p.lastIndex=0;return p.test(a)?'"'+a.replace(p,function(a){var c=r[a];return typeof c==="string"?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function l(a,j){var c,d,h,m,g=e,f,b=j[a];b&&typeof b==="object"&&typeof b.toJSON==="function"&&(b=b.toJSON(a));typeof i==="function"&&(b=i.call(j,a,b));switch(typeof b){case "string":return o(b);case "number":return isFinite(b)?String(b):"null";case "boolean":case "null":return String(b);case "object":if(!b)return"null";
e+=n;f=[];if(Object.prototype.toString.apply(b)==="[object Array]"){m=b.length;for(c=0;c<m;c+=1)f[c]=l(c,b)||"null";h=f.length===0?"[]":e?"[\n"+e+f.join(",\n"+e)+"\n"+g+"]":"["+f.join(",")+"]";e=g;return h}if(i&&typeof i==="object"){m=i.length;for(c=0;c<m;c+=1)typeof i[c]==="string"&&(d=i[c],(h=l(d,b))&&f.push(o(d)+(e?": ":":")+h))}else for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(h=l(d,b))&&f.push(o(d)+(e?": ":":")+h);h=f.length===0?"{}":e?"{\n"+e+f.join(",\n"+e)+"\n"+g+"}":"{"+f.join(",")+
"}";e=g;return h}}if(typeof Date.prototype.toJSON!=="function")Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+k(this.getUTCMonth()+1)+"-"+k(this.getUTCDate())+"T"+k(this.getUTCHours())+":"+k(this.getUTCMinutes())+":"+k(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var q=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
p=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,e,n,r={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},i;if(typeof JSON.stringify!=="function")JSON.stringify=function(a,j,c){var d;n=e="";if(typeof c==="number")for(d=0;d<c;d+=1)n+=" ";else typeof c==="string"&&(n=c);if((i=j)&&typeof j!=="function"&&(typeof j!=="object"||typeof j.length!=="number"))throw Error("JSON.stringify");return l("",
{"":a})};if(typeof JSON.parse!=="function")JSON.parse=function(a,e){function c(a,d){var g,f,b=a[d];if(b&&typeof b==="object")for(g in b)Object.prototype.hasOwnProperty.call(b,g)&&(f=c(b,g),f!==void 0?b[g]=f:delete b[g]);return e.call(a,d,b)}var d,a=String(a);q.lastIndex=0;q.test(a)&&(a=a.replace(q,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return d=eval("("+a+")"),typeof e==="function"?c({"":d},""):d;throw new SyntaxError("JSON.parse");}})();
/*
* jquery.iecors.js
*/
(function(b){b.ajaxSettings.xdr=function(){return window.XDomainRequest?new window.XDomainRequest:null};(function(a){b.extend(b.support,{iecors:!!a})})(b.ajaxSettings.xdr());b.support.iecors&&b.ajaxTransport(function(a){return{send:function(b,d){var c=a.xdr();c.onload=function(){d(200,"OK",{text:c.responseText},{"Content-Type":c.contentType})};if(a.xhrFields)xhr.onerror=a.xhrFields.error,xhr.ontimeout=a.xhrFields.timeout;c.open(a.type,a.url);c.send(a.hasContent&&a.data||null)},abort:function(){xdr.abort()}}})})(jQuery);
/*
* jquery.easydate.js
*/
(function(b){function e(f,b,a){!isNaN(b)&&b!=1&&(f+="s");return a.locale[f]||f}b.easydate={};b.easydate.locales={};b.easydate.locales.enUS={future_format:"%s %t",past_format:"%t %s",second:"second",seconds:"seconds",minute:"minute",minutes:"minutes",hour:"hour",hours:"hours",day:"day",days:"days",week:"week",weeks:"weeks",month:"month",months:"months",year:"year",years:"years",yesterday:"yesterday",tomorrow:"tomorrow",now:"just now",ago:"ago","in":"in"};b.easydate.locales.esCA={future_format:"%s %t",
past_format:"%s %t",second:"segon",seconds:"segons",minute:"minut",minutes:"minuts",hour:"hora",hours:"hores",day:"dia",days:"dies",week:"setmana",weeks:"setmanes",month:"mes",months:"mesos",year:"any",years:"anys",yesterday:"ahir",tomorrow:"dem\u00e0",now:"fa un moment",ago:"fa","in":"en"};var i={live:!0,set_title:!0,format_future:!0,format_past:!0,units:[{name:"now",limit:5},{name:"second",limit:60,in_seconds:1},{name:"minute",limit:3600,in_seconds:60},{name:"hour",limit:86400,in_seconds:3600},
{name:"yesterday",limit:172800,past_only:!0},{name:"tomorrow",limit:172800,future_only:!0},{name:"day",limit:604800,in_seconds:86400},{name:"week",limit:2629743,in_seconds:604800},{name:"month",limit:31556926,in_seconds:2629743},{name:"year",limit:Infinity,in_seconds:31556926}],uneasy_format:function(b){return b.toLocaleDateString()},locale:b.easydate.locales.esCA};b.easydate.format_date=function(f,h){var a=b.extend({},i,h),c=((new Date).getTime()-f.getTime())/1E3,g=Math.abs(c);if(!isNaN(c)&&!(!a.format_future&&
c<0||!a.format_past&&c>0)){for(var j in a.units){var d=a.units[j];if(!(d.past_only&&c<0||d.future_only&&c>0)&&g<d.limit){if(isNaN(d.in_seconds))return e(d.name,NaN,a);g/=d.in_seconds;g=Math.round(g);return(c<0?e("future_format",NaN,a).replace("%s",e("in",NaN,a)):e("past_format",NaN,a).replace("%s",e("ago",NaN,a))).replace("%t",g+" "+e(d.name,g,a))}}return a.uneasy_format(f)}}})(jQuery);
/*
* hogan.js
*/
var HoganTemplate=function(){function n(a){this.text=a}n.prototype={r:function(){return""},v:function(a){a=String(a===null?"":a);return s.test(a)?a.replace(u,"&amp;").replace(v,"&lt;").replace(w,"&gt;").replace(l,"&#39;").replace(j,"&quot;"):a},render:function(a,c,f){return this.r(a,c,f)},rp:function(a,c,f,e){a=f[a];return!a?"":a.r(c,f,e)},rs:function(a,c,f){var e="",g=a[a.length-1];if(!p(g))return f(a,c);for(var b=0;b<g.length;b++)a.push(g[b]),e+=f(a,c),a.pop();return e},s:function(a,c,f,e,g,b,i){if(p(a)&&
a.length===0)return!1;!e&&typeof a=="function"&&(a=this.ls(a,c,f,g,b,i));f=a===""||!!a;!e&&f&&c&&c.push(typeof a=="object"?a:c[c.length-1]);return f},d:function(a,c,f,e){var g=a.split("."),b=this.f(g[0],c,f,e),i=null;if(a==="."&&p(c[c.length-2]))return c[c.length-1];for(a=1;a<g.length;a++)b&&typeof b=="object"&&g[a]in b?(i=b,b=b[g[a]]):b="";if(e&&!b)return!1;!e&&typeof b=="function"&&(c.push(i),b=this.lv(b,c,f),c.pop());return b},f:function(a,c,f,e){for(var g=!1,b=null,i=!1,m=c.length-1;m>=0;m--)if((b=
c[m])&&typeof b=="object"&&a in b){g=b[a];i=!0;break}if(!i)return e?!1:"";!e&&typeof g=="function"&&(g=this.lv(g,c,f));return g},ho:function(a,c,f,e,g){a=a.call(c,e,function(b){return Hogan.compile(b,{delimiters:g}).render(c,f)});this.b=Hogan.compile(a.toString(),{delimiters:g}).render(c,f);return!1},b:"",ls:function(a,c,f,e,g,b){var c=c[c.length-1],i=a.call(c);return a.length>0?this.ho(a,c,f,this.text.substring(e,g),b):typeof i=="function"?this.ho(i,c,f,this.text.substring(e,g),b):i},lv:function(a,
c,f){c=c[c.length-1];return Hogan.compile(a.call(c).toString()).render(c,f)}};var u=/&/g,v=/</g,w=/>/g,l=/\'/g,j=/\"/g,s=/[&<>\"\']/,p=Array.isArray||function(a){return Object.prototype.toString.call(a)==="[object Array]"};return n}(),Hogan=function(){function n(b,a){function m(){o.length>0&&(k.push(new String(o)),o="")}function c(b,a){m();var d;if(d=b)a:{d=!0;for(var i=n;i<k.length;i++)if(d=k[i].tag&&g[k[i].tag]<g._v||!k[i].tag&&k[i].match(p)===null,!d){d=!1;break a}}if(d){d=n;for(var f;d<k.length;d++)if(!k[d].tag){if((f=
k[d+1])&&f.tag==">")f.indent=k[d].toString();k.splice(d,1)}}else a||k.push({tag:"\n"});j=!1;n=k.length}function d(b,a){var d="="+q,m=b.indexOf(d,a),c=u(b.substring(b.indexOf("=",a)+1,m)).split(" ");r=c[0];q=c[1];return m+d.length-1}var f=b.length,e=0,t=null,l=null,o="",k=[],j=!1,h=0,n=0,r="{{",q="}}";a&&(a=a.split(" "),r=a[0],q=a[1]);for(h=0;h<f;h++)e==0?v(r,b,h)?(--h,m(),e=1):b.charAt(h)=="\n"?c(j):o+=b.charAt(h):e==1?(h+=r.length-1,t=(l=g[b.charAt(h+1)])?b.charAt(h+1):"_v",t=="="?(h=d(b,h),e=0):
(l&&h++,e=2),j=h):v(q,b,h)?(k.push({tag:t,n:u(o),otag:r,ctag:q,i:t=="/"?j-q.length:h+r.length}),o="",h+=q.length-1,e=0,t=="{"&&h++):o+=b.charAt(h);c(j,!0);return k}function u(b){return b.trim?b.trim():b.replace(/^\s*|\s*$/g,"")}function v(b,a,m){if(a.charAt(m)!=b.charAt(0))return!1;for(var c=1,d=b.length;c<d;c++)if(a.charAt(m+c)!=b.charAt(c))return!1;return!0}function w(b,a,c,f){for(var a=[],d=null,e=null;b.length>0;){e=b.shift();if(!(d=e.tag=="#"))if(!(d=e.tag=="^"))a:{for(var d=e,g=f,j=0,l=g.length;j<
l;j++)if(g[j].o==d.n){d.tag="#";d=!0;break a}d=void 0}if(d)c.push(e),e.nodes=w(b,e.tag,c,f),a.push(e);else if(e.tag=="/"){if(c.length===0)throw Error("Closing tag without opener: /"+e.n);d=c.pop();if(b=e.n!=d.n){var o;a:{b=0;for(c=f.length;b<c;b++)if(f[b].c==e.n&&f[b].o==d.n){o=!0;break a}}b=!o}if(b)throw Error("Nesting error: "+d.n+" vs. "+e.n);d.end=e.i;return a}else a.push(e)}if(c.length>0)throw Error("missing closing tag: "+c.pop().n);return a}function l(b){return b.replace(e,"\\\\").replace(a,
'\\"').replace(c,"\\n").replace(f,"\\r")}function j(b){return~b.indexOf(".")?"d":"f"}function s(b){for(var a="",c=0,e=b.length;c<e;c++){var d=b[c].tag;if(d=="#"){var d=b[c].nodes,f=j(b[c].n),g=b[c].i,n=b[c].end,p=b[c].otag+" "+b[c].ctag,d="if(_.s(_."+f+'("'+l(b[c].n)+'",c,p,1),c,p,0,'+g+","+n+', "'+p+'")){b += _.rs(c,p,function(c,p){ var b = "";'+s(d)+'return b;});c.pop();}else{b += _.b; _.b = ""};';a+=d}else d=="^"?(d=b[c].nodes,d="if (!_.s(_."+j(b[c].n)+'("'+l(b[c].n)+'",c,p,1),c,p,1,0,0,"")){'+
s(d)+"};",a+=d):d=="<"||d==">"?a+='b += _.rp("'+l(b[c].n)+'",c[c.length - 1],p,"'+(b[c].indent||"")+'");':d=="{"||d=="&"?(d="b += (_."+j(b[c].n)+'("'+l(b[c].n)+'",c,p,0));',a+=d):d=="\n"?a+='b += "\\n"'+(b.length-1==c?"":" + i")+";":d=="_v"?(d="b += (_.v(_."+j(b[c].n)+'("'+l(b[c].n)+'",c,p,0)));',a+=d):d===void 0&&(d='"'+l(b[c])+'"',a+="b += "+d+";")}return a}var p=/\S/,a=/\"/g,c=/\n/g,f=/\r/g,e=/\\/g,g={"#":1,"^":2,"/":3,"!":4,">":5,"<":6,"=":7,_v:8,"{":9,"&":10};return{scan:n,parse:function(b,a){a=
a||{};return w(b,"",[],a.sectionTags||[])},cache:{},compile:function(b,a){var a=a||{},c=this.cache[b];if(c)return c;var e=this.parse(n(b,a.delimiters),a),c=a,e='i = i || "";var c = [cx];var b = i + "";var _ = this;'+s(e)+"return b;";c.asString?c="function(cx,p,i){"+e+";}":(c=new HoganTemplate(b),c.r=new Function("cx","p","i",e));return this.cache[b]=c}}}();
if(typeof module!=="undefined"&&module.exports)module.exports=Hogan,module.exports.Template=HoganTemplate;else if(typeof define==="function"&&define.amd)define(function(){return Hogan});else if(typeof exports!=="undefined")exports.Hogan=Hogan,exports.HoganTemplate=HoganTemplate;
/*
* max.templates.js
*/
var MSTCH_MAXUI_MAIN_UI='<div id="maxui-container">{{#username}} <div id="maxui-mainpanel">   <div id="maxui-search" class="folded">       <a id="maxui-search-toggle" class="maxui-disabled" href="#"><img src="https://max.upc.edu/maxui/transparent.gif" alt="obre-tanca" ></a>       <div id="maxui-search-box">          <input id="maxui-search-text" type="search" placeholder="{{literals.search_text}}" class="maxui-empty maxui-text-input" value="{{literals.search_text}}" />          <\!--<input disabled="disabled" id="maxui-search-action" type="button" class="maxui-button maxui-disabled"></input>--\>       </div>       <div id="maxui-search-filters"></div>   </div>   <div id="maxui-timeline">      <div class="wrapper">          <div id="maxui-preload" class="activities" style="height:0px;overflow:hidden">              <div class="wrapper">              </div>          </div>          <div id="maxui-activities" class="activities">          </div>          <div id="maxui-more-activities">              <input type="button" class="maxui-button" value="{{literals.load_more}}">          </div>      </div>   </div>  </div> </div>{{/username}}{{^username}}  No s\'ha definit cap usuari{{/username}}</div>',
MSTCH_MAXUI_POSTBOX='   {{#allowPosting}}   <div id="maxui-newactivity">      <a href="{{profile}}" class="maxui-avatar">          <img src="{{avatar}}">      </a>      <div id="maxui-newactivity-box">           <textarea class="maxui-empty maxui-text-input">{{literals.new_activity_text}}</textarea>           <input disabled="disabled" type="button" class="maxui-button maxui-disabled" value="{{literals.new_activity_post}}">      </div>   </div>   {{/allowPosting}}',MSTCH_MAXUI_ACTIVITY='<div class="maxui-activity" id="{{id}}" userid="{{actor.id}}" username="{{actor.username}}">    <div class="maxui-activity-content">        <div class="maxui-publisheddate">{{date}}</div>        <div class="maxui-author">          <a href="{{profileURL}}">           \t\t<span class="maxui-avatar"><img src="{{avatarURL}}"></span>\t\t          <span class="maxui-displayname">{{actor.displayName}}</span>          </a>          <span class="maxui-username">{{actor.username}}</span>        </div>        <div>            <p class="maxui-body">{{&text}}</p>        </div>        <div class="maxui-publisheddate"></div>    </div>    <div class="maxui-footer">        <div class="maxui-origin">               {{#publishedIn}}                   {{literals.context_published_in}}                   <a href="{{publishedIn.url}}">{{publishedIn.displayName}}</a>               {{/publishedIn}}               {{#via}}                   {{literals.generator_via}}                   <span class="maxui-via">                   {{via}}                   </span>               {{/via}}        </div>        <div class="maxui-actions">            <a href="" class="maxui-commentaction">                 {{#replies}}<strong>{{replies.totalItems}}</strong>{{/replies}}                 {{^replies}}<strong>0</strong>{{/replies}}                 {{literals.toggle_comments}}            </a>                    </div>    </div>    <div class="maxui-comments" style="display: none">        <div class="maxui-commentsbox">            {{#replies.items}}                {{> comment}}            {{/replies.items}}        </div>        <div class="maxui-newcommentbox">                <textarea class="maxui-empty maxui-text-input" id="maxui-commentBox">{{literals.new_comment_text}}</textarea>                <input disabled="disabled" type="button" class="maxui-button maxui-disabled" value="{{literals.new_comment_post}}"/>        </div>    </div>    <div class="maxui-clear"></div></div>',
MSTCH_MAXUI_COMMENT='<div class="maxui-comment" id="{{id}}" userid="{{author.id}}" displayname="{{author.username}}">    <div class="maxui-activity-content">        <div class="maxui-publisheddate">{{date}}</div>        <div class="maxui-author">\t   <a href="{{profileURL}}">\t\t<span class="maxui-avatar"><img src="{{avatarURL}}"></span>\t\t<span class="maxui-displayname">{{author.displayName}}</span></a> \t   <span class="maxui-username">{{author.username}}</span>        </div>        <div>            <p class="maxui-body">{{&text}}</p>        </div>        <div class="maxui-publisheddate"></div>    </div></div>',
MSTCH_MAXUI_FILTERS='{{#filters}}<div class="maxui-filter maxui-{{type}}" type="{{type}}" value="{{value}}"><span>{{prepend}}{{value}}<a class="close" href=""><img src="https://max.upc.edu/maxui/x.png" alt="tanca"></a></span></div>{{/filters}}',MAXUI_MAIN_UI=Hogan.compile(MSTCH_MAXUI_MAIN_UI),MAXUI_POSTBOX=Hogan.compile(MSTCH_MAXUI_POSTBOX),MAXUI_ACTIVITY=Hogan.compile(MSTCH_MAXUI_ACTIVITY),MAXUI_COMMENT=Hogan.compile(MSTCH_MAXUI_COMMENT),MAXUI_FILTERS=Hogan.compile(MSTCH_MAXUI_FILTERS);
/*
* max.client.js
*/
if(!Object.keys)Object.keys=function(a){var b=[],c;for(c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.push(c);return b};String.prototype.format=function(){var a=arguments;return this.replace(/\{\d+\}/g,function(b){return a[b.match(/\d+/)]})};
function MaxClient(a){this.url=a;this.mode="jquery";this.ROUTES={users:"/people",user:"/people/{0}",avatar:"/people/{0}/avatar",user_activities:"/people/{0}/activities",timeline:"/people/{0}/timeline",user_comments:"/people/{0}/comments",user_shares:"/people/{0}/shares",user_likes:"/people/{0}/likes",follows:"/people/{0}/follows",follow:"/people/{0}/follows/{1}",subscriptions:"/people/{0}/subscriptions",activities:"/activities",activity:"/activities/{0}",comments:"/activities/{0}/comments",comment:"/activities/{0}/comments/{1}",
likes:"/activities/{0}/likes",like:"/activities/{0}/likes/{1}",shares:"/activities/{0}/shares",share:"/activities/{0}/shares/{1}"}}MaxClient.prototype.setMode=function(a){this.mode=a};MaxClient.prototype.setActor=function(a){this.actor={objectType:"person",username:a}};
MaxClient.prototype.POST=function(a,b,c){resource_uri="{0}{1}".format(this.url,a);this.mode=="jquery"?jQuery.ajax({url:resource_uri,beforeSend:function(a){a.setRequestHeader("X-Oauth-Token",_MAXUI.settings.oAuthToken);a.setRequestHeader("X-Oauth-Username",_MAXUI.settings.username);a.setRequestHeader("X-Oauth-Scope","widgetcli")},type:"POST",data:JSON.stringify(b),async:!0,dataType:"json"}).done(function(a){c.call(a)}).fail(function(a){jQuery(window).trigger("maxclienterror",a)}):(a={},a[gadgets.io.RequestParameters.CONTENT_TYPE]=
gadgets.io.ContentType.JSON,a[gadgets.io.RequestParameters.METHOD]=gadgets.io.MethodType.POST,a[gadgets.io.RequestParameters.REFRESH_INTERVAL]=1,a[gadgets.io.RequestParameters.POST_DATA]=JSON.stringify(b),a[gadgets.io.RequestParameters.HEADERS]={"X-Oauth-Token":_MAXUI.settings.oAuthToken,"X-Oauth-Username":_MAXUI.settings.username,"X-Oauth-Scope":"widgetcli"},console.log(a),gadgets.io.makeRequest(resource_uri,function(a){c.call(a.data)},a));return!0};
MaxClient.prototype.GET=function(a,b,c){resource_uri="{0}{1}".format(this.url,a);caca=this;Object.keys(b).length>0&&(resource_uri+="?"+jQuery.param(b,!0));this.mode=="jquery"?jQuery.ajax({url:resource_uri,beforeSend:function(a){a.setRequestHeader("X-Oauth-Token",_MAXUI.settings.oAuthToken);a.setRequestHeader("X-Oauth-Username",_MAXUI.settings.username);a.setRequestHeader("X-Oauth-Scope","widgetcli")},type:"GET",async:!0,dataType:"json"}).done(function(a){c.call(a)}).fail(function(a){jQuery(window).trigger("maxclienterror",
a)}):(a={},a[gadgets.io.RequestParameters.CONTENT_TYPE]=gadgets.io.ContentType.JSON,a[gadgets.io.RequestParameters.METHOD]=gadgets.io.MethodType.GET,a[gadgets.io.RequestParameters.REFRESH_INTERVAL]=1,a[gadgets.io.RequestParameters.HEADERS]={"X-Oauth-Token":_MAXUI.settings.oAuthToken,"X-Oauth-Username":_MAXUI.settings.username,"X-Oauth-Scope":"widgetcli"},gadgets.io.makeRequest(resource_uri,function(a){console.log(data);c.call(a.data)},a));return!0};
MaxClient.prototype.getUserTimeline=function(a,b){this.GET(this.ROUTES.timeline.format(a),arguments.length>2?arguments[2]:{},b)};MaxClient.prototype.getUserData=function(a,b){this.GET(this.ROUTES.user.format(a),{},b)};MaxClient.prototype.getActivities=function(a,b,c){var d=this.ROUTES.activities;query=arguments.length>3?arguments[3]:{};if(b)query.context=b;this.GET(d,query,c)};MaxClient.prototype.getCommentsForActivity=function(a,b){route=this.ROUTES.comments.format(a);this.GET(route,{},b)};
MaxClient.prototype.addComment=function(a,b,c){var d={actor:{},object:{objectType:"comment",content:""}};d.actor=this.actor;d.object.content=a;route=this.ROUTES.comments.format(b);this.POST(route,d,c)};MaxClient.prototype.addActivity=function(a,b,c){query={object:{objectType:"note",content:""}};if(b.length>0)query.contexts=b;query.object.content=a;if(arguments.length>3)query.generator=arguments[3];route=this.ROUTES.user_activities.format(this.actor.username);this.POST(route,query,c)};
MaxClient.prototype.follow=function(a){query={object:{objectType:"person",username:""}};query.object.username=a;route=this.ROUTES.follow.format(this.actor.username,a);resp=this.POST(route,query)};
/*
* max.ui.js
*/
(function(b){b.fn.maxUI=function(a){var e=this;if(!window._MAXUI)window._MAXUI={};var d=b.extend({new_activity_text:"Write something...",new_activity_post:"Post activity",toggle_comments:"Comments",new_comment_text:"Comment something...",new_comment_post:"Post comment",load_more:"Load more",context_published_in:"Published in",generator_via:"via",search_text:"Search..."},a.literals);delete a.literals;_MAXUI.settings=b.extend({maxRequestsAPI:"jquery",maxServerURL:"http://max.beta.upcnet.es",readContext:"",
writeContexts:[],activitySource:"timeline",literals:d,enableAlerts:!1},a);if(!this.isCORSCapable()&&_MAXUI.settings.maxServerURLAlias)_MAXUI.settings.maxServerURL=_MAXUI.settings.maxServerURLAlias;_MAXUI.settings.writeContexts.push(_MAXUI.settings.readContext);_MAXUI.settings.readContextHash=e.sha1(_MAXUI.settings.readContext);_MAXUI.settings.avatarURLpattern||(_MAXUI.settings.avatarURLpattern=_MAXUI.settings.maxServerURL+"/people/{0}/avatar");_MAXUI.settings.profileURLpattern||(_MAXUI.settings.profileURLpattern=
_MAXUI.settings.maxServerURL+"/profiles/{0}");_MAXUI.settings.enableAlerts&&b(window).bind("maxclienterror",function(c,a){var b=JSON.parse(a.responseText);alert('The server responded with a "{0}" error, with the following message: "{1}". \n\nPlease try again later or contact administrator at admin@max.upc.edu.'.format(b.error,b.error_description))});this.maxClient=new MaxClient(_MAXUI.settings.maxServerURL);this.maxClient.setMode(_MAXUI.settings.maxRequestsAPI);this.maxClient.setActor(_MAXUI.settings.username);
this.maxClient.getUserData(_MAXUI.settings.username,function(){var a={};if(this.subscribedTo&&this.subscribedTo.items&&this.subscribedTo.items.length>0)for(sc=0;sc<this.subscribedTo.items.length;sc++){var d=this.subscribedTo.items[sc];a[d.url]={};a[d.url].permissions={};for(pm=0;pm<d.permissions.length;pm++)a[d.url].permissions[d.permissions[pm]]=!0}window._MAXUI.settings.subscriptions=a;a=MAXUI_MAIN_UI.render({username:_MAXUI.settings.username,literals:_MAXUI.settings.literals});e.html(a);e.printActivities({},
function(){b("#maxui-more-activities .maxui-button").click(function(a){a.preventDefault();b("#maxui-search").hasClass("folded")?e.loadMoreActivities():(last_result_id=b(".maxui-activity:last").attr("id"),e.reloadFilters(last_result_id))});b("#maxui-search-toggle").click(function(a){a.preventDefault();b(this).hasClass("maxui-disabled")||(b("#maxui-search").toggleClass("folded"),b("#maxui-search").hasClass("folded")?e.printActivities({}):e.reloadFilters())});b("#maxui-activities").on("click",".maxui-commentaction",
function(a){a.preventDefault();window.status="";b(this).closest(".maxui-activity").find(".maxui-comments").toggle(200)});b("#maxui-activities").on("click",".maxui-hashtag",function(a){a.preventDefault();e.addFilter({type:"hashtag",value:b(this).attr("value")});b("#maxui-search").toggleClass("folded",!1)});b("#maxui-search-filters").on("click",".close",function(a){a.preventDefault();a=b(this.parentNode.parentNode);e.delFilter({type:a.attr("type"),value:a.attr("value")})});e.bindActionBehaviour("#maxui-newactivity",
"#maxui-newactivity-box",_MAXUI.settings.literals.new_activity_text,function(a){e.sendActivity(a);b("#maxui-search").toggleClass("folded",!0)});e.bindActionBehaviour("#maxui-activities",".maxui-newcommentbox",_MAXUI.settings.literals.new_comment_text,function(a){var c=b(this).closest(".maxui-activity").attr("id");e.maxClient.addComment(a,c,function(){b("#activityContainer textarea").val("");var a=this.object.inReplyTo[0].id;e.printCommentsForActivity(a);b("#"+a+" .maxui-newcommentbox textarea").val("");
b("#"+a+" .maxui-newcommentbox .maxui-button").attr("disabled","disabled")})});e.bindActionBehaviour("#maxui-search","#maxui-search-box",_MAXUI.settings.literals.search_text,function(a){e.textSearch(a);b("#maxui-search").toggleClass("folded",!1)});b("#maxui-search .maxui-text-input").keyup(function(a){a.keyCode==13&&(e.textSearch(b(this).attr("value")),b("#maxui-search").toggleClass("folded",!1))})})});return e};b.fn.bindActionBehaviour=function(a,e,d,c){var g=this,j=e+" .maxui-text-input";b(a).on("focusin",
j,function(a){a.preventDefault();text=b(this).val();normalized=g.normalizeWhiteSpace(text,!1);normalized==d&&b(this).val("")}).on("keyup",j,function(a){a.preventDefault();text=b(this).val();button=b(this).parent().find(".maxui-button");normalized=g.normalizeWhiteSpace(text,!1);normalized==""?(b(button).attr("disabled","disabled"),b(button).attr("class","maxui-button maxui-disabled"),b(this).attr("class","maxui-empty maxui-text-input")):(b(button).removeAttr("disabled"),b(button).attr("class","maxui-button"),
b(this).attr("class","maxui-text-input"))}).on("focusout",j,function(a){a.preventDefault();text=b(this).val();normalized=g.normalizeWhiteSpace(text,!1);normalized==""&&b(this).val(d)}).on("click",e+" .maxui-button",function(a){a.preventDefault();var a=b(this).parent().find(".maxui-text-input").val(),e=g.normalizeWhiteSpace(a,!1);e!=d&e!=""&&c.apply(this,[a])})};b.fn.normalizeWhiteSpace=function(a,b){var a=a.replace(/(^\s*)|(\s*jq)/gi,""),a=a.replace(/\n /,"\n"),d=!0;arguments.length>1&&(d=b);d==!0&&
(a=a.replace(/[ ]{2,}/gi," "));return a};b.fn.textSearch=function(a){normalized=this.normalizeWhiteSpace(a);a=normalized.split(" ");for(kw=0;kw<a.length;kw++){var b="keyword",d=a[kw];d[0]=="#"&&(b="hashtag",d=d.substr(1));d.length>=3&&this.addFilter({type:b,value:d},!1)}this.reloadFilters()};b.fn.reloadFilters=function(){var a={filters:window._MAXUI.filters},e=MAXUI_FILTERS.render(a);b("#maxui-search-filters").html(e);e={};for(f=0;f<a.filters.length;f++){var d=a.filters[f];e[d.type]||(e[d.type]=[]);
e[d.type].push(d.value)}arguments.length>0&&(e.before=arguments[0]);this.printActivities(e);b("#maxui-search-toggle").toggleClass("maxui-disabled",window._MAXUI.filters.length==0);b("#maxui-search").toggleClass("folded",window._MAXUI.filters.length==0)};b.fn.delFilter=function(a){var b=!1;for(i=0;i<window._MAXUI.filters.length;i++)window._MAXUI.filters[i].value==a.value&window._MAXUI.filters[i].type==a.type&&(b=!0,window._MAXUI.filters.splice(i,1));b&&this.reloadFilters()};b.fn.addFilter=function(a){var b=
!0;arguments.length>1&&(b=arguments[1]);if(!window._MAXUI.filters)window._MAXUI.filters=[];switch(a.type){case "hashtag":a.prepend="#";break;default:a.prepend=""}var d=!1;for(i=0;i<window._MAXUI.filters.length;i++)window._MAXUI.filters[i].value==a.value&window._MAXUI.filters[i].type==a.type&&(d=!0);d||(window._MAXUI.filters.push(a),b==!0&&this.reloadFilters())};b.fn.isCORSCapable=function(){return(new XMLHttpRequest).withCredentials!=void 0?!0:!1};b.fn.Settings=function(){return maxui.settings};b.fn.sendActivity=
function(){maxui=this;var a=b("#maxui-newactivity textarea").val(),e=[];e.push(a);e.push(_MAXUI.settings.writeContexts);e.push(function(){b("#maxui-newactivity textarea").val("");b("#maxui-newactivity .maxui-button").attr("disabled","disabled");var a=b(".maxui-activity:first");a.length>0?(filter={after:a.attr("id")},maxui.printActivities(filter)):maxui.printActivities({})});_MAXUI.settings.generatorName&&e.push(_MAXUI.settings.generatorName);maxui.maxClient.addActivity.apply(maxui.maxClient,e)};b.fn.loadMoreActivities=
function(){maxui=this;filter={before:b(".maxui-activity:last").attr("id")};maxui.printActivities(filter)};b.fn.formatDate=function(a){var e=new Date;if(a=a.match("^([-+]?)(\\d{4,})(?:-?(\\d{2})(?:-?(\\d{2})(?:[Tt ](\\d{2})(?::?(\\d{2})(?::?(\\d{2})(?:\\.(\\d{1,3})(?:\\d+)?)?)?)?(?:[Zz]|(?:([-+])(\\d{2})(?::?(\\d{2}))?)?)?)?)?)?$")){for(var d=[2,3,4,5,6,7,8,10,11],c=d.length-1;c>=0;--c)a[d[c]]=typeof a[d[c]]!="undefined"&&a[d[c]].length>0?parseInt(a[d[c]],10):0;a[1]=="-"&&(a[2]*=-1);d=Date.UTC(a[2],
a[3]-1,a[4],a[5],a[6],a[7],a[8]);typeof a[9]!="undefined"&&a[9].length>0&&(d+=(a[9]=="+"?-1:1)*(a[10]*36E5+a[11]*6E4));a[2]>=0&&a[2]<=99&&(d-=59958144E6);e.setTime(d);return formatted=b.easydate.format_date(e)}else return null};b.fn.utf8_decode=function(a){var b=[],d=0,c=0,g=0,j=0,m=0;for(a+="";d<a.length;)g=a.charCodeAt(d),g<128?(b[c++]=String.fromCharCode(g),d++):g>191&&g<224?(j=a.charCodeAt(d+1),b[c++]=String.fromCharCode((g&31)<<6|j&63),d+=2):(j=a.charCodeAt(d+1),m=a.charCodeAt(d+2),b[c++]=String.fromCharCode((g&
15)<<12|(j&63)<<6|m&63),d+=3);return b.join("")};b.fn.formatActivities=function(a,e){var d="";for(i=0;i<a.length;i++){var c=a[i],g=void 0;c.hasOwnProperty("contexts")&&c.contexts.length>0&&(g=c.contexts[0]);var j=void 0;if(c.hasOwnProperty("generator")&&c.generator!=_MAXUI.settings.generatorName)j=c.generator;var m=void 0;if(c.replies&&(m={totalItems:c.replies.totalItems,items:[]},c.replies.items.length>0))for(r=0;r<c.replies.items.length;r++){var n=c.replies.items[r];reply={id:n.id,author:n.author,
date:this.formatDate(n.published),text:this.formatText(n.content),avatarURL:_MAXUI.settings.avatarURLpattern.format(n.author.username),profileURL:_MAXUI.settings.profileURLpattern.format(n.author.username)};m.items.push(reply)}c={id:c.id,actor:c.actor,literals:_MAXUI.settings.literals,date:this.formatDate(c.published),text:this.formatText(c.object.content),replies:m,avatarURL:_MAXUI.settings.avatarURLpattern.format(c.actor.username),profileURL:_MAXUI.settings.profileURLpattern.format(c.actor.username),
publishedIn:g,via:j};d+=MAXUI_ACTIVITY.render(c,{comment:MAXUI_COMMENT})}if(e=="beggining"){b("#maxui-preload .wrapper").prepend(d);g=b("#maxui-preload .wrapper .maxui-activity");for(i=c=0;i<g.length;i++)c+=b(g[i]).height()+18;g=b("#maxui-preload").height();b("#maxui-preload").height(c-g);b("#maxui-preload").css({"margin-top":(c-g)*-1});b("#maxui-preload").animate({"margin-top":0},200,function(){b("#maxui-preload .wrapper").html("");b("#maxui-activities").prepend(d);b("#maxui-preload").height(0)})}else e==
"end"?b("#maxui-activities").append(d):b("#maxui-activities").html(d);arguments.length>2&&arguments[2].call()};b.fn.formatComment=function(a,e){maxui=this;var d="";for(i=0;i<a.length;i++){var c=a[i],c={literals:_MAXUI.settings.literals,id:c.id,author:c.author,date:maxui.formatDate(c.published),text:maxui.formatText(c.content),avatarURL:_MAXUI.settings.avatarURLpattern.format(c.author.username),profileURL:_MAXUI.settings.profileURLpattern.format(c.author.username)};d+=MAXUI_COMMENT.render(c)}b(".maxui-activity#"+
e+" .maxui-commentsbox").html(d);comment_count=b(".maxui-activity#"+e+" .maxui-commentaction strong");b(comment_count).text(eval(b(comment_count).text())+1)};b.fn.formatText=function(a){a&&(a=a.replace(/((https?\:\/\/)|(www\.))(\S+)(\w{2,4})(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/gi,function(a){var b=a;b.match("^https?://")||(b="http://"+b);return'<a href="'+b+'">'+a+"</a>"}),a=a.replace(/(\s|^)#{1}(\w+)/gi,function(a,b,c){return'<a class="maxui-hashtag" value="'+c+'" href="{0}/{}">#'+c+" </a>"}));
return a};b.fn.sha1=function(a){function b(a,c){return a<<c|a>>>32-c}function d(a){var b="",c,d;for(c=7;c>=0;c--)d=a>>>c*4&15,b+=d.toString(16);return b}var c,g,j=Array(80),m=1732584193,n=4023233417,s=2562383102,t=271733878,u=3285377520,h,k,l,o,p,a=function(a){for(var a=a.replace(/\r\n/g,"\n"),b="",c=0;c<a.length;c++){var d=a.charCodeAt(c);d<128?b+=String.fromCharCode(d):(d>127&&d<2048?b+=String.fromCharCode(d>>6|192):(b+=String.fromCharCode(d>>12|224),b+=String.fromCharCode(d>>6&63|128)),b+=String.fromCharCode(d&
63|128))}return b}(a);h=a.length;var q=[];for(c=0;c<h-3;c+=4)g=a.charCodeAt(c)<<24|a.charCodeAt(c+1)<<16|a.charCodeAt(c+2)<<8|a.charCodeAt(c+3),q.push(g);switch(h%4){case 0:c=2147483648;break;case 1:c=a.charCodeAt(h-1)<<24|8388608;break;case 2:c=a.charCodeAt(h-2)<<24|a.charCodeAt(h-1)<<16|32768;break;case 3:c=a.charCodeAt(h-3)<<24|a.charCodeAt(h-2)<<16|a.charCodeAt(h-1)<<8|128}for(q.push(c);q.length%16!=14;)q.push(0);q.push(h>>>29);q.push(h<<3&4294967295);for(a=0;a<q.length;a+=16){for(c=0;c<16;c++)j[c]=
q[a+c];for(c=16;c<=79;c++)j[c]=b(j[c-3]^j[c-8]^j[c-14]^j[c-16],1);g=m;h=n;k=s;l=t;o=u;for(c=0;c<=19;c++)p=b(g,5)+(h&k|~h&l)+o+j[c]+1518500249&4294967295,o=l,l=k,k=b(h,30),h=g,g=p;for(c=20;c<=39;c++)p=b(g,5)+(h^k^l)+o+j[c]+1859775393&4294967295,o=l,l=k,k=b(h,30),h=g,g=p;for(c=40;c<=59;c++)p=b(g,5)+(h&k|h&l|k&l)+o+j[c]+2400959708&4294967295,o=l,l=k,k=b(h,30),h=g,g=p;for(c=60;c<=79;c++)p=b(g,5)+(h^k^l)+o+j[c]+3395469782&4294967295,o=l,l=k,k=b(h,30),h=g,g=p;m=m+g&4294967295;n=n+h&4294967295;s=s+k&4294967295;
t=t+l&4294967295;u=u+o&4294967295}p=d(m)+d(n)+d(s)+d(t)+d(u);return p.toLowerCase()};b.fn.printActivities=function(a){var e=this,d=[],c="replace";a.before&&(c="end");a.after&&(c="beggining");if(_MAXUI.settings.activitySource=="timeline"){var g=this.maxClient.getUserTimeline;d.push(_MAXUI.settings.username)}else if(_MAXUI.settings.activitySource=="activities")g=this.maxClient.getActivities,d.push(_MAXUI.settings.username),d.push(_MAXUI.settings.readContextHash);if(arguments.length>1){var j=arguments[1];
d.push(function(){var a=!0,d=_MAXUI.settings.subscriptions;if(!d[this.context.url])d[this.context.url]={},d[this.context.url].permissions={},d[this.context.url].permissions.read=this.context.permissions.read=="public",d[this.context.url].permissions.write=!1;for(wc=0;wc<_MAXUI.settings.writeContexts.length;wc++){var g=_MAXUI.settings.writeContexts[wc];d[g].permissions?d[g].permissions.write==!1&&(a=!1):a=!1}a&&(a=b.extend(_MAXUI.settings,{avatar:_MAXUI.settings.avatarURLpattern.format(_MAXUI.settings.username),
profile:_MAXUI.settings.profileURLpattern.format(_MAXUI.settings.username),allowPosting:a,literals:_MAXUI.settings.literals}),a=MAXUI_POSTBOX.render(a),jQuery("#maxui-mainpanel").prepend(a));e.formatActivities(this.items,c,j)})}else d.push(function(){e.formatActivities(this.items,c)});d.push(a);g.apply(this.maxClient,d)};b.fn.printCommentsForActivity=function(a){var b=this,d=[];d.push(a);d.push(function(){b.formatComment(this.items,a)});this.maxClient.getCommentsForActivity.apply(this.maxClient,d)}})(jQuery);
/*
* max.loader.js
*/
window.setTimeout(function () {
    if(window._MAXUI.onReady && !window._MAXUI.hasRun){
        window._MAXUI.hasRun = true;
        _MAXUI.onReady();
    }
  },0)
