modify_context = 'Can modify context'
list_contexts = 'List contexts'
list_public_contexts = 'List public contexts'
add_context = 'Add context'
delete_context = 'Delete context'
view_context = 'View context'
view_context_activity = 'View context activity'

add_people = 'Add people'
list_all_people = 'List all people'
list_visible_people = 'List visible people'
view_user_profile = 'View user profile'
modify_user = 'Modify user profile'
delete_user = 'Delete user'

add_subscription = 'Subscribe an user to a context'
remove_subscription = 'Unsubscribe an user to a context'
manage_subcription_permissions = 'Grant or revoke permissions on a subscription'
view_subscriptions = 'View all subscriptions of peple to a context'
